### ISSUE TITLE
Input fields for logging in with author name and secret

### ISSUE THREAD

**Issue by cinnamon-bun** [sgwilym/earthstar-lobby#2]
Uploading an author keypair as a JSON file is cool, I hadn't thought of that!

It would be nice to also have a pair of traditional "username" / "password" inputs for entering the same information, in case someone is keeping it in their password manager.

(Earthstar calls these "author address" and "author secret" but I think apps can just say "username" and "password" since people are familiar with that metaphor already.)

**Comment by sgwilym** [comment]
@cinnamon-bun Thanks! There's a part of me that even thought about obscuring the json part of it altogether, instead having files like `gwil.author`...

So regarding having a traditional username/password UI for this, I get what you're saying re: familiarity. But it might be misleading, because a username/password UI usually comes with other assumptions, like the UI being able to tell you if you entered the wrong password. We could validate that the address and secret are the right shape, but how would the client be able to tell a user if they'd entered the wrong secret for the given address? Validate it against an existing document (assuming there is one)?

I feel like how earthstar handles identity gives us the possibility to do something _better_ than what users currently expect. I'm not saying uploading a json file is it, but having your identity be like a single opaque token has some interesting potential in it.

**Comment by cinnamon-bun** [comment]
> how would the client be able to tell a user if they'd entered the wrong secret for the given address? 

Good point!  I've just added a function to check if the secret and pubkey are a matching set:

[`crypto.checkAuthorKeypairIsValid(keypair)`](https://github.com/earthstar-project/earthstar/blob/master/src/crypto/crypto.ts#L88-L120)

---

I have opinions ™️ !

**Familiarity**

Re-using concepts that people are familiar with is huge for usability.  I think people have a mental budget of, like, 2 new concepts when trying out a new tool.

For that reason, Earthstar identities are as close to username/passwords as possible:
* They have a public part that identifies you; you can choose it (somewhat); and you can share it safely with others
* There's a part you have to keep secret
* When you log in, you supply these 2 parts into 2 text fields

There are differences and we will need to educate users about them:
* The password is chosen for you
* You can't change it
* You can't recover from forgetting it

**If you use a password manager**

...everything is great, it works easily and your secret is safe.

**If you don't...**

...then you're in trouble.  How do you remember this enormous password?

An identity JSON file is a great solution to this problem!  Files are really not safe places to keep passwords, but if you don't have a password manager it's the next best thing.

Personally I would not keep a password in a file, and I have no way of safely getting it to my other devices except by using my password manager.

---

So my preference is
* Have traditional username / password fields that are recognized by password managers
* Also have JSON file support for people who don't use password managers
* Add some help text like:

> Earthstar passwords are kind of different: we choose one for you, you can't change it, and you can't recover if you forget it.  Make sure not to lose your password!

**Comment by sgwilym** [comment]
I'm on board with this. It will have to wait until I refactor and redesign a bit to support more complex UIs for options here.

**Comment by sgwilym** [comment]
Closed thanks to the Earthbar!
