### ISSUE TITLE
Sort by original date vs. edit date

### ISSUE THREAD

**Issue by cinnamon-bun** [sgwilym/earthstar-lobby#3]
It could be nice to sort posts by their original date instead of last-edited, so they stay in the same place when you edit them.

The original timestamp is in the path.  If the timestamp came first, like `/lobby/158105938/~@cinn.bxxxxxxxxx`, you could just sort them by path.

**Comment by sgwilym** [comment]
@cinnamon-bun  Yes, this makes sense to me too!

I could implement this the way you suggest, but I have two thoughts:

1. This approach hinges on the client having _all_ documents available to sort.
2. Sorting documents by the original publication date seems like a pattern that clients will want regularly, and requiring them to implement it themselves every time seems like it could be prone to error.

To expand on point one: at some point earthstar-graphql is going to return [paginated connections](https://relay.dev/graphql/connections.htm) for documents rather than any array with every document ever in it. There will still be ways to get every result in a single request, and I think this can be a valid approach with a client-side schema, but there are definitely UIs and situations you'll want only a portion of a workspace's documents at a time. At that point, you can't do things like client-side sorting of documents by publication date, because you won't have all docs available.

Secondly, if clients do this themselves they'll always have to store the timestamp somewhere, either in the document path or content, and for such a common use-case that seems a bit much to me.

I guess what I'm driving at is: could/should earthstar documents have an original publication date field?

**Comment by cinnamon-bun** [comment]
You're right!  There will be a lot of cases like this where clients want to query by something that's not part of the core Document schema yet.  Tags, categories, threads, creation timestamp, ...

I want to keep the core schema as small as possible, just what's needed for replication, so the specification can be stable.

I was considering adding a `metadata` object that you could easily query:

```
{
    path: "/posts/~@suzy.bxxxxx/a93nhf-23jf9f-faj093j",
    content: "OMG so true",
    timestamp: 15000000077777,  // when updated
    metadata: {
        // put your own data here and it will be queryable
        creationTimestamp: 15000000000001,
        category: "intros",
        parentPost: "/posts/~@moth.bxxxxx/d923j-ajw049f-j328fa",
    }
}
```

More details in https://github.com/earthstar-project/earthstar/issues/9

**Comment by sgwilym** [comment]
Oh, nice. How do you imagine querying for that, would that be an extra field on `QueryOpts`?

**Comment by cinnamon-bun** [comment]
Yes, some built-in way to query and sort by this metadata.  (Although we're on the verge of creating a full-fledged query language and I'd love to avoid that complexity.)

**Comment by sgwilym** [comment]
I will do this the naive way by sorting all documents for now 😄
