### ISSUE TITLE
Display name details

### ISSUE THREAD

**Issue by cinnamon-bun** [sgwilym/earthstar-lobby#4]
Woo display names!  🎉 

* Setting a display name doesn't trigger the "unsaved changes" message that reminds you to sync.
* Maybe show the display name in the top right by the clock, instead of the shortname?
* Would be interesting to try out a Twitter style design on posts, showing both the display name and author address.  It's overkill for this simple app but in a bigger app it would help people learn both names so they could notice imposters and easily @-mention people by shortname:

```
Cinnamon
@cinn.ba0830fha...

Hello world
```

BTW you can ignore [the Earthstar spec](https://github.com/earthstar-project/earthstar/blob/master/docs/specification.md#author-profiles) which says display names go in a JSON document at `/about/@suzy.bxxxxx/profile.json` along with some other profile info.  I'm thinking about breaking this back up into separate documents for each property, like you're doing (`.../name`).

**Comment by sgwilym** [comment]
Phew, I saw the diff for earthstar 5.1.0 and thought "d'oh!". I was following what the vocabulary doc said about long names prior.

Regarding the name in the top right: because users can use a single author keypair across many workspaces, I'd like interfaces to reflect that. Only showing the display name could make users think they have separate identities between workspaces.

For the same reason I'd like to show short names in post titles too, but for that I'm seeing where the conversation in https://github.com/earthstar-project/earthstar/issues/41 leads to!

**Comment by cinnamon-bun** [comment]
Re: https://github.com/earthstar-project/earthstar/issues/41 -- added those helper functions for deterministic randomness in [5.2.1 (see release notes)](https://github.com/earthstar-project/earthstar/releases/tag/v5.2.1)

**Comment by sgwilym** [comment]
With the old manual sync UI superseded + both display and short names shown, I guess it's safe to close this.
